### ISSUE TITLE
indexing support

### ISSUE THREAD

**Issue by jaberg** [hyperopt/searchspaces#7]
Pyll supports indexing like `scope.list([1, 2, 3])[2]`. This has also been useful for things like
`a, b, c = scope.list([1, 2, 3])` which is related.

What are your thoughts on indexing with partialplus objects?

``` python
partial(list, [1, 2, 3])[2]  # simple, supports slicing possibly confusing
partial(list, [1, 2, 3]).partial_getitem(2)  # clear, but no slice syntax support
partial(list, [1, 2, 3]).idxview[:2]  # another possibility...
```

so far I think the first option is the best even if some people might have other ideas for what indexing a partial should do.

**Comment by dwf** [comment]
Already supported, I think? If you run as_partialplus on a list and index
it to should get the right thing.

**Comment by dwf** [comment]
``` python
In [1]: from searchspaces.export.pyll import as_pyll

In [2]: from searchspaces.partialplus import as_partialplus

In [3]: a = as_partialplus([5, 3, 9])[2]

In [4]: a
Out[4]: <searchspaces.partialplus.PartialPlus at 0x35902b8>

In [5]: a
Out[5]: <searchspaces.partialplus.PartialPlus at 0x35902b8>

In [6]: as_pyll(a)
Out[6]: <hyperopt.pyll.base.Apply at 0x358b3d0>

In [7]: as_pyll(a)
Out[7]: <hyperopt.pyll.base.Apply at 0x358b390>

In [8]: print as_pyll(a)
0 _getitem
1   pos_args
2     Literal{5}
3     Literal{3}
4     Literal{9}
5   Literal{2}
```

**Comment by jaberg** [comment]
perfect

On Thu, May 8, 2014 at 1:59 PM, David Warde-Farley <notifications@github.com

**Comment by dwf** [comment]
I might want to sub in `hyperopt.pyll.getitem` instead of `searchspaces.partialplus._getitem` but yeah, that's pretty much it.

**Comment by jaberg** [comment]
That would be a nice touch, but I think it's fine for hyperopt to depend on
searchspaces when the original graph is coming from searchspaces.

On Thu, May 8, 2014 at 2:10 PM, David Warde-Farley <notifications@github.com
